name: thomastang
favicon: null
layout_spectrum: 0.24207
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#000000'
    - '#d9d9d9'
    - '#434343'
    - '#838383'
  brandStrength: 0.5
  lightness: 0.9833585452288389
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
