name: thomastang
favicon: null
layout_spectrum: 0.4758300771936774
typography_spectrum: 0.9618188599124551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#000000'
    - '#d9d9d9'
    - '#434343'
    - '#838383'
  brandStrength: 0
  lightness: 0.9833585452288389
  saturation: 0.9903317883145064
  rhythmicContrast: 0.8470036822836846
purpose: []
